name: CI/CD for Flask and Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend Setup: Python and Flask
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          # Assuming you have tests written in a test folder
          pytest

      # Frontend Setup: Node.js for running frontend tools (if necessary)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend  # Navigate to your frontend folder
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build  # Customize if you have a specific build command

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test  # Customize for frontend testing framework, e.g., Jest

      # Deploy to Heroku (if all tests pass)
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/main'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Log in to Heroku CLI
          echo $HEROKU_API_KEY | heroku auth:token --app <YOUR_HEROKU_APP_NAME>
          # Deploy the app
          git push heroku main
